import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {Hero} from '../components'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Jungo Digital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero heading='Jungo Digital' message='We provide the hand force for your home.' />
    </div>
  )
}
