import Head from 'next/head';
import Image from 'next/image';

import { Hero, Navbar } from '../components';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Jungo Digital</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar logoName="Jungo Digital" />
			<Hero
				heading="Frontend Developer."
				message="A frontend developer building things for the web which leads to the success of client's overall product"
			/>
		</div>
	);
}
